import { Product } from "../types/products";

export const products: Product[] = [
	{
        id: "1",
		title: "Футболка",
		description: "Сидит точно по размеру",
		price: 17,
		count: 22,
		image: "https://picsum.photos/300", 
    },
    {
        id: "2",
		title: "Носки",
		description: "Сидит точно по размеру",
		price: 7,
		count: 22,
		image: "https://picsum.photos/300", 
    },
    {
        id: "3",
		title: "Шапка",
		description: "Сидит точно по размеру",
		price: 37,
		count: 26,
		image: "https://picsum.photos/300", 
    },
    {
        id: "4",
		title: "Маска",
		description: "Сидит точно по размеру",
		price: 11,
		count: 72,
		image: "https://picsum.photos/300", 
    },
    {
        id: "5",
		title: "Очки",
		description: "Сидит точно по размеру",
		price: 13,
		count: 2,
		image: "https://picsum.photos/300", 
    },
    {
        id: "6",
		title: "Шорты",
		description: "Сидит точно по размеру",
		price: 17,
		count: 1,
		image: "https://picsum.photos/300", 
    },
    {
        id: "7",
		title: "Кружка",
		description: "Сидит точно по размеру",
		price: 18,
		count: 73,
		image: "https://picsum.photos/300", 
    },
    {
        id: "8",
		title: "Ручка",
		description: "Сидит точно по размеру",
		price: 17,
		count: 64,
		image: "https://picsum.photos/300", 
    },
    {
        id: "9",
		title: "Блокнот",
		description: "Сидит точно по размеру",
		price: 12,
		count: 12,
		image: "https://picsum.photos/300", 
    },
];
